/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ccho' at '1/19/16 10:28 AM' with Gradle 2.6
 *
 * @author ccho, @date 1/19/16 10:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
